name: Example CI CD by Panov
on:
  push:
    branches:
    - master
    - panov
    
jobs:
  build-job:
    runs-on: ubuntu-latest
    
    steps:
    # Пример однолинейного простого скрипта shell
    - name: Run a one-line script
      run: echo Hello, world!

    # Пример многолинейного скрипта shell
    - name: Run a multi-line script
      run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "Hello, $GITLAB_USER_LOGIN!"
